[base]
mode = "repository"
smart_pull = true

[mode.repository]
name = "blend-x86_64"
build_on_update = false

[mode.repository.signing]
enabled = true

[mode.workspace]
git_info = true
colorblind = false

[repositories]
repos = [
    "bos:blend-pkg",
    "bos:almost-pkg",
    "bos:os-installer-pkg",
    "bos:os-installer-config",
    "bos:filesystem-blend",
    "bos:lsb-release-blend",
    "bos:gnome-kiosk",
    "bos:mesa-tweaks-blend",
    "bos:firefox-tweaks-blend",
    "bos:flatpak-init-blend-pkg",
    "bos:plymouth-pkg",
    "bos:blend-keyring-pkg"
]

[repositories.urls]
bos = "https://github.com/blend-os/{}"
aur = "https://aur.archlinux.org/{}"
